# Sample from electron-builder: https://www.electron.build/multi-platform-build#sample-travisyml-to-build-electron-app-for-macos-linux-and-windows
# Fixed deployment with travis-cli: ``travis setup releases``
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "lts/*" # Use latest LTS Node.js release
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: linux
      language: node_js
      node_js: "lts/*"
    - os: windows
      language: node_js
      node_js: "lts/*"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  # Install yarn on all OS
  - yarn

script:
  # Build release for github-pages once on linux
  - yarn run build
  # Build multi-OS binaries (using "Vue CLI Plugin Electron Builder")
  - yarn run electron:build

branches:
  only:
  - releases

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "suhrmann"
  - git config --local user.email ""
  - export TRAVIS_TAG=${$(node -p "require('$TRAVIS_BUILD_DIR/package.json').version")-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  # Github pages
  - provider: pages
    skip-cleanup: true
    local_dir: dist
    github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
    keep-history: true
    on:
      branch: releases

  # Github releases
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: aWO+C1FB7xcrRWY5O3gtAug0xoVrKO3e5Hw/FKOIxjlmeUp+49bq/jsCIdRNJuWj+Mdz1bnWxeTbDmBUCb80FZ5Wda3MNupxYoaVZuCxAKvdWOgJI571OzJ7TWa/uO5t7z57w726bOhx5KWRytECSsJTBZyUvR/o4iZG+A3fH3Ry/nRU/yc+R6E/Hly9djltk3opFZCRRrwiFgyDCXqN95fA5H4ANIQDRKxwLDlvtLJfYBQMjBSnOF8sPPJss/z5yFLdDsNvyUgy7NlRcC9bCiM9DWsHcy0uSFDg2ACZWgN7rgGQfCudT8/9Abtmhm6HtdUczaz8DsC86cQPafGqGMgHi22pWfyP2N0kWe5eZdE5UEvOtK+G9p6p7S1fhCMt27qgqm3PY4P5TryT0bq0HiVMti3YtQM/ZpNGwvbmYMXJfxJEG/rLTvIBM6yvo7q2Nn5ctkcZhRc9xg7TfZTrEbvQPAcA1tEKEQgMnZJYEyaetjB/zlJ6BIvZPpIz6kqoiNc3VN8EYzQo+bvP2f6okcH1L0aAKqrAY/k8NHtYQwRlC/UmIrddNnkTDayQoYLjLPixOMdIhgCJfUoulWdPyDQbb8S2bHCYdsLLA0grUJKHgQAb/L7JajziCD+DBB245mrTdt11Z13s8GqRzDmLUpV4xKjJoPM/H8mU+yK2vZE=
    file_glob: true
    file:
      - "dist_electron/*.exe" # Windows
      - "dist_electron/*.dmg" # MacOS
      - "dist_electron/*.AppImage" # Linux
      - "dist_electron/*.snap" # Linux
    on:
      repo: suhrmann/Anno-1800-Calculator
      branch: releases
